elixirs:
  elixir_speed:
    name: Speed Elixir
    required_rank: 0
    result:
      type: POTION
      potion_effect: SPEED
      duration: 60       # seconds
      amplifier: 1       # Speed II
    actions:
      - action: ADD
        ingredient_name: WHEAT_SEEDS
        amount: 2

      - action: SET_TEMPERATURE
        amount: 30

      - action: BOIL
        duration: 5

      - action: STIR_CLOCKWISE
        amount: 3

      - action: ADD
        ingredient_name: ACACIA_BOAT
        amount: 1

      - action: STIR_COUNTERCLOCKWISE
        amount: 2

      - action: WAIT
        duration: 4